<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsuarioSeeder extends Seeder
{
    public function run(): void
    {
        $roles = DB::table('roles')->pluck('id', 'nombre');

        $tipoIdentificacionId = DB::table('tipos_identificacion')
            ->where('abreviacion', 'CC')
            ->value('id');

        $usuarios = [
            [
                'nombre' => 'Admin',
                'apellido' => 'Admin',
                'email' => 'admin@admin.com',
                'numero_identificacion' => '123456789',
                'contraseña' => Hash::make('admin'),
                'rol_id' => $roles['Admin'],
                'imagen_path' => 'usuarios/admin.png',
                'telefono' => '3178711309',
            ],
            [
                'nombre' => 'Leonardo',
                'apellido' => 'Ramírez',
                'email' => 'leonardo.ramirez@chess.com',
                'numero_identificacion' => '112198041',
                'contraseña' => Hash::make('presidente'),
                'rol_id' => $roles['Presidente Liga'],
                'imagen_path' => 'usuarios/presidente_liga.png',
                'telefono' => '3104567821',
            ],
            [
                'nombre' => 'Martín',
                'apellido' => 'Martínez Romero',
                'email' => 'martin.martinez@chess.com',
                'numero_identificacion' => '1015823490',
                'contraseña' => Hash::make('presidente'),
                'rol_id' => $roles['Presidente Club'],
                'imagen_path' => 'usuarios/presidente_club1.png',
                'telefono' => '3197894325',
            ],
            [
                'nombre' => 'Javier',
                'apellido' => 'Marroquín',
                'email' => 'javier.marroquin@chess.com',
                'numero_identificacion' => '1123456789',
                'contraseña' => Hash::make('presidente'),
                'rol_id' => $roles['Presidente Club'],
                'imagen_path' => 'usuarios/presidente_club2.png',
                'telefono' => '3125678934',
            ],
            [
                'nombre' => 'Yobani',
                'apellido' => 'González',
                'email' => 'yobani.gonzalez@chess.com',
                'numero_identificacion' => '1124567890',
                'contraseña' => Hash::make('presidente'),
                'rol_id' => $roles['Presidente Club'],
                'imagen_path' => 'usuarios/presidente_club3.png',
                'telefono' => '3136789045',
            ],
            [
                'nombre' => 'Guillermo',
                'apellido' => 'Rey',
                'email' => 'guillermo.rey@chess.com',
                'numero_identificacion' => '1125678901',
                'contraseña' => Hash::make('presidente'),
                'rol_id' => $roles['Presidente Club'],
                'imagen_path' => 'usuarios/presidente_club4.png',
                'telefono' => '3147890156',
            ],
            [
                'nombre' => 'Carlos',
                'apellido' => 'Rodríguez',
                'email' => 'carlos.rodriguez@chess.com',
                'numero_identificacion' => '1126789012',
                'contraseña' => Hash::make('entrenador'),
                'rol_id' => $roles['Entrenador'],
                'imagen_path' => 'usuarios/entrenador1.png',
                'telefono' => '3158901267',
            ],
            [
                'nombre' => 'Andrés',
                'apellido' => 'Morales',
                'email' => 'andres.morales@chess.com',
                'numero_identificacion' => '1127890123',
                'contraseña' => Hash::make('entrenador'),
                'rol_id' => $roles['Entrenador'],
                'imagen_path' => 'usuarios/entrenador2.png',
                'telefono' => '3169012378',
            ],
            [
                'nombre' => 'Diego',
                'apellido' => 'Castro',
                'email' => 'diego.castro@chess.com',
                'numero_identificacion' => '1128901234',
                'contraseña' => Hash::make('entrenador'),
                'rol_id' => $roles['Entrenador'],
                'imagen_path' => 'usuarios/entrenador3.png',
                'telefono' => '3170123489',
            ],
            [
                'nombre' => 'Felipe',
                'apellido' => 'Vargas',
                'email' => 'felipe.vargas@chess.com',
                'numero_identificacion' => '1129012345',
                'contraseña' => Hash::make('entrenador'),
                'rol_id' => $roles['Entrenador'],
                'imagen_path' => 'usuarios/entrenador4.png',
                'telefono' => '3181234590',
            ],

            [
                'nombre' => 'Magnus',
                'apellido' => 'Carlsen',
                'email' => 'magnus.carlsen@chess.com',
                'numero_identificacion' => '9011304819',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3190005682',
            ],
            [
                'nombre' => 'Fabiano',
                'apellido' => 'Caruana',
                'email' => 'fabiano.caruana@chess.com',
                'numero_identificacion' => '9207301102',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3158970032',
            ],
            [
                'nombre' => 'Hikaru',
                'apellido' => 'Nakamura',
                'email' => 'hikaru.nakamura@chess.com',
                'numero_identificacion' => '8712094491',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3159997621',
            ],
            [
                'nombre' => 'Javokhir',
                'apellido' => 'Sindarov',
                'email' => 'javokhir.sindarov@chess.com',
                'numero_identificacion' => '0512088831',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3227622489',
            ],
            [
                'nombre' => 'Vincent',
                'apellido' => 'Keymer',
                'email' => 'vincent.keymer@chess.com',
                'numero_identificacion' => '0411153392',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3108642785',
            ],
            [
                'nombre' => 'Wesley',
                'apellido' => 'So',
                'email' => 'wesley.so@chess.com',
                'numero_identificacion' => '9310095510',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3117651294',
            ],
            [
                'nombre' => 'Anish',
                'apellido' => 'Giri',
                'email' => 'anish.giri@chess.com',
                'numero_identificacion' => '9406287721',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3023323400',
            ],
            [
                'nombre' => 'Nodirbek',
                'apellido' => 'Abdusattorov',
                'email' => 'nodirbek.abdusattorov@chess.com',
                'numero_identificacion' => '0409181092',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3028763452',
            ],
            [
                'nombre' => 'Arjun',
                'apellido' => 'Erigaisi',
                'email' => 'arjun.erigaisi@chess.com',
                'numero_identificacion' => '0309036621',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3028904312',
            ],
            [
                'nombre' => 'Alireza',
                'apellido' => 'Firouzja',
                'email' => 'alireza.firouzja@chess.com',
                'numero_identificacion' => '0306182281',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3025429016',
            ],
            [
                'nombre' => 'Faustino',
                'apellido' => 'Oro',
                'email' => 'faustino.oro@chess.com',
                'numero_identificacion' => '52891002',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3204892563',
            ],
            [
                'nombre' => 'Santiago',
                'apellido' => 'López Rayo',
                'email' => 'santiago.lopez@chess.com',
                'numero_identificacion' => '1018452910',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3211258792',
            ],
            [
                'nombre' => 'Manuel',
                'apellido' => 'Campos Gómez',
                'email' => 'manuel.campos@chess.com',
                'numero_identificacion' => '1020394811',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3224568211',
            ],
            [
                'nombre' => 'Sebastián Felipe',
                'apellido' => 'Sánchez',
                'email' => 'sebastian.sanchez@chess.com',
                'numero_identificacion' => '1012938471',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3102675491',
            ],
            [
                'nombre' => 'Esteban',
                'apellido' => 'Valderrama Quiceno',
                'email' => 'esteban.valderrama@chess.com',
                'numero_identificacion' => '1037612890',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3201239854',
            ],
            [
                'nombre' => 'Jairo Andrés',
                'apellido' => 'Hernández Sánchez',
                'email' => 'jairo.hernandez@chess.com',
                'numero_identificacion' => '1019283746',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3158996655',
            ],
            [
                'nombre' => 'Cristian Andrés',
                'apellido' => 'Hernández',
                'email' => 'cristian.hernandez@chess.com',
                'numero_identificacion' => '1014728391',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3108996666',
            ],
            [
                'nombre' => 'Ángel Gabriel',
                'apellido' => 'Córdoba Roa',
                'email' => 'angel.cordoba@chess.com',
                'numero_identificacion' => '1022839102',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3124443278',
            ],
            [
                'nombre' => 'Levy',
                'apellido' => 'Rozman',
                'email' => 'levy.rozman@chess.com',
                'numero_identificacion' => '9512058821',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '310000000',
            ],
            [
                'nombre' => 'José Gabriel',
                'apellido' => 'Cardoso Cardoso',
                'email' => 'jose.cardoso@chess.com',
                'numero_identificacion' => '1019384720',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3108764521',
            ],
            [
                'nombre' => 'Jaime Alexander',
                'apellido' => 'Cuartas',
                'email' => 'jaime.cuartas@chess.com',
                'numero_identificacion' => '71283940',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3218993564',
            ],
            [
                'nombre' => 'Santiago',
                'apellido' => 'Ávila Pavas',
                'email' => 'santiago.avila@chess.com',
                'numero_identificacion' => '1017283941',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3128905642',
            ],
            [
                'nombre' => 'Andrés Felipe',
                'apellido' => 'Gallego Alcaraz',
                'email' => 'andres.gallego@chess.com',
                'numero_identificacion' => '1012384920',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3117895362',
            ],
            [
                'nombre' => 'Roberto',
                'apellido' => 'García Pantoja',
                'email' => 'roberto.garcia@chess.com',
                'numero_identificacion' => '1035829102',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3102867432',
            ],
            [
                'nombre' => 'Sergio E.',
                'apellido' => 'Barrientos',
                'email' => 'sergio.barrientos@chess.com',
                'numero_identificacion' => '98765432',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3164789253',
            ],
            [
                'nombre' => 'Joshua Daniel',
                'apellido' => 'Ruiz Castillo',
                'email' => 'joshua.ruiz@chess.com',
                'numero_identificacion' => '1018293840',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3119908374',
            ],
            [
                'nombre' => 'Alder',
                'apellido' => 'Escobar Forero',
                'email' => 'alder.escobar@chess.com',
                'numero_identificacion' => '79823104',
                'contraseña' => Hash::make('deportista'),
                'rol_id' => $roles['Deportista'],
                'imagen_path' => null,
                'telefono' => '3229005400',
            ],
        ];

        foreach ($usuarios as $usuario) {
            $usuario['tipo_identificacion_id'] = $tipoIdentificacionId;
            $usuario['created_at'] = now();
            $usuario['updated_at'] = now();

            DB::table('usuarios')->updateOrInsert(
                ['email' => $usuario['email']],
                $usuario
            );
        }

        DB::statement("
            SELECT setval(
                pg_get_serial_sequence('usuarios', 'id'),
                COALESCE((SELECT MAX(id) FROM usuarios), 1)
            )
        ");
    }
}
